#!/usr/bin/env bash
set -euo pipefail

cd /var/www/html

seed_database="false"

# Never reuse package manifests generated by a host install with dev dependencies.
rm -f bootstrap/cache/packages.php bootstrap/cache/services.php
php artisan package:discover --ansi

if [ ! -f .env ]; then
    cp .env.example .env
fi

if ! grep -q '^APP_KEY=base64:' .env; then
    php artisan key:generate --force --no-interaction
fi

mkdir -p storage/framework/{cache,sessions,testing,views} storage/logs bootstrap/cache
chown -R www-data:www-data storage bootstrap/cache

if [ "${DB_CONNECTION:-}" = "sqlite" ]; then
    sqlite_path="${DB_DATABASE:-/var/www/html/database/database.sqlite}"
    if [ ! -f "$sqlite_path" ] || [ ! -s "$sqlite_path" ]; then
        seed_database="true"
    fi
    mkdir -p "$(dirname "$sqlite_path")"
    touch "$sqlite_path"
    chown www-data:www-data "$sqlite_path"
fi

if [ "${RUN_MIGRATIONS:-true}" = "true" ]; then
    php artisan migrate --force --no-interaction

    if [ "${FORCE_DB_SEED:-false}" = "true" ] || [ "$seed_database" = "true" ]; then
        php artisan db:seed --class="${DB_SEEDER_CLASS:-Database\\Seeders\\DatabaseSeeder}" --force --no-interaction
        php artisan moon:copy
    fi
fi

php artisan storage:link --force

exec "$@"
