version: '3'
rpc:
  listen: 'tcp://127.0.0.1:6001'
server:
  command: ""
  relay: pipes
http:
  middleware: [ "static", "gzip", "headers" ]
  max_request_size: 20
  access_logs: false
  static:
    dir: "public"
    forbid: [ ".php", ".htaccess" ]
  uploads:
    forbid: [".php", ".exe", ".bat", ".sh"]
  address: "0.0.0.0:2114"
  pool:
    allocate_timeout: 10s
    destroy_timeout: 10s
    supervisor:
      max_worker_memory: 256
      exec_ttl: 60s
## 这里注意如果要输出标准输出必须在 channels 才会写 stdout
logs:
  mode: production
  level: debug
  encoding: console
  output: stderr
  err_output: stderr
  channels:
    http:
      mode: production
      level: panic
      encoding: console
      output: stdout
      err_output: stderr
    server:
      mode: production
      level: info
      encoding: json
      output: stdout
      err_output: stdout
    rpc:
      mode: production
      level: debug
      encoding: console
      output: stderr
      err_output: stdout
status:
    address: localhost:2114
