@extends('layouts.modern')

@section('title', $product->name.' 秒杀 - Monday Shop')

@section('main')
<section class="shop-container py-12 lg:py-16"><div class="grid gap-10 lg:grid-cols-2"><div class="overflow-hidden rounded-[2.5rem] bg-slate-100"><img src="{{ assertUrl($product->thumb) }}" alt="{{ $product->name }}" class="aspect-square h-full w-full object-cover"></div><div class="py-4"><span class="shop-kicker">Flash sale</span><h1 class="mt-3 text-4xl font-black">{{ $product->name }}</h1><div class="mt-6 flex items-end gap-3"><strong class="text-4xl text-rose-600">¥{{ number_format($redisSeckill->price, 2) }}</strong><del class="pb-1 text-slate-400">¥{{ number_format($product->price, 2) }}</del></div><div class="mt-6 grid grid-cols-2 gap-4"><div class="shop-card p-5"><p class="text-xs text-slate-400">活动库存</p><p class="mt-1 text-2xl font-black">{{ $redisSeckill->number }}</p></div><button id="buyers-button" class="shop-card p-5 text-left"><p class="text-xs text-slate-400">已抢购</p><p class="mt-1 text-2xl font-black">{{ $redisSeckill->sale_count }}</p></button></div>
@auth<label class="mt-6 grid gap-2 text-sm font-bold">收货地址 @if($addresses->isNotEmpty())<select id="seckill-address" class="shop-input">@foreach($addresses as $address)<option value="{{ $address->id }}" @selected($address->is_default)>{{ $address->name }} / {{ $address->phone }} / {{ $address->format() }}</option>@endforeach</select>@else<a class="text-brand-600" href="{{ url('/user/addresses') }}">先添加收货地址 →</a>@endif</label><div id="seckill-message" class="mt-5 hidden rounded-2xl px-4 py-3 text-sm font-semibold"></div><button id="seckill-button" class="shop-button-primary mt-6 w-full" data-seconds="{{ $redisSeckill->is_start ? 0 : $redisSeckill->diff_time }}" @disabled($addresses->isEmpty())>{{ $redisSeckill->is_start ? '立即抢购' : '活动即将开始' }}</button>@else<div class="mt-7 rounded-2xl bg-slate-50 p-5 text-sm text-slate-600">登录后即可参与秒杀。 <a href="{{ url('/login') }}" class="font-black text-brand-600">立即登录</a></div>@endauth</div></div></section>
@endsection

@push('scripts')
<script>
const seckillButton = document.querySelector('#seckill-button'); let seconds = Number(seckillButton?.dataset.seconds || 0);
const formatCountdown = (value) => { const days = Math.floor(value / 86400); const hours = Math.floor(value % 86400 / 3600); const minutes = Math.floor(value % 3600 / 60); const secs = Math.floor(value % 60); return `${days}天 ${String(hours).padStart(2,'0')}:${String(minutes).padStart(2,'0')}:${String(secs).padStart(2,'0')}`; };
if (seckillButton && seconds > 0) { seckillButton.disabled = true; seckillButton.textContent = formatCountdown(seconds); const timer = setInterval(() => { seconds -= 0.5; seckillButton.textContent = formatCountdown(Math.max(0, seconds)); if (seconds <= 0) { clearInterval(timer); seckillButton.disabled = false; seckillButton.textContent = '立即抢购'; } }, 500); }
seckillButton?.addEventListener('click', async () => { const message = document.querySelector('#seckill-message'); seckillButton.disabled = true; seckillButton.textContent = '抢购中...'; try { const { data } = await axios.post('/user/seckills/{{ $redisSeckill->id }}', { address_id: document.querySelector('#seckill-address')?.value }); if (Number(data.code) !== 200) throw new Error(data.msg || '抢购失败'); document.open(); document.write(data.data.form); document.close(); } catch (error) { seckillButton.disabled = false; seckillButton.textContent = '立即抢购'; message.textContent = error.response?.data?.msg || error.message || '抢购失败'; message.className = 'mt-5 rounded-2xl bg-rose-50 px-4 py-3 text-sm font-semibold text-rose-700'; } });
document.querySelector('#buyers-button')?.addEventListener('click', async () => { const { data } = await axios.get('/seckills/{{ $redisSeckill->id }}/users'); alert(Number(data.code) === 200 ? (data.data.join('\n') || '还没有人抢购') : data.msg); });
</script>
@endpush
