@extends('layouts.account')
@section('title', '我的订单 · Monday Shop')
@section('account')
<div class="flex flex-wrap items-end justify-between gap-4"><div><p class="text-xs font-bold uppercase tracking-[0.2em] text-brand-600">Orders</p><h1 class="mt-3 text-3xl font-black">我的订单</h1></div><a href="{{ url('/products') }}" class="text-sm font-bold text-brand-700">继续购物 →</a></div>
<div class="mt-7 flex gap-2 overflow-x-auto pb-2">@foreach([[0,'全部',$ordersCount],[1,'待付款',$unPayCount],[2,'待发货',$shipPendingCount],[3,'待收货',$shipDeliveredCount],[4,'待评价',$shipReceivedCount]] as [$tab,$label,$count])<a href="?tab={{ $tab }}" class="whitespace-nowrap rounded-full px-4 py-2 text-sm font-bold {{ (int)request('tab',0)===$tab ? 'bg-slate-950 text-white' : 'border border-slate-300 bg-white text-slate-600' }}">{{ $label }} {{ $count }}</a>@endforeach</div>
@if($errors->any())<div class="mt-4 rounded-2xl bg-rose-50 p-4 text-sm text-rose-700">{{ $errors->first() }}</div>@endif
@if(session('status'))<div class="mt-4 rounded-2xl bg-brand-50 p-4 text-sm text-brand-700">{{ session('status') }}</div>@endif
<div class="mt-6 grid gap-5">
@forelse($orders as $order)
<article class="overflow-hidden rounded-[2rem] border border-slate-200 bg-white"><header class="flex flex-wrap items-center justify-between gap-3 border-b border-slate-100 px-5 py-4 sm:px-7"><div><a href="{{ url('/user/orders/'.$order->id) }}" class="text-sm font-black">订单 {{ $order->no }}</a><p class="mt-1 text-xs text-slate-400">{{ $order->created_at }}</p></div><span class="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold">{{ $order->status_text }}</span></header><div class="divide-y divide-slate-100 px-5 sm:px-7">@foreach($order->details as $detail)<div class="flex gap-4 py-5"><a href="{{ url('/products/'.$detail->product->uuid) }}" class="size-20 shrink-0 overflow-hidden rounded-2xl bg-slate-100"><img src="{{ $detail->product->thumb }}" alt="" class="h-full w-full object-cover"></a><div class="min-w-0 flex-1"><a href="{{ url('/products/'.$detail->product->uuid) }}" class="line-clamp-2 text-sm font-bold">{{ $detail->product->name }}</a><p class="mt-3 text-xs text-slate-400">¥{{ number_format($detail->price,2) }} × {{ $detail->number }}</p></div></div>@endforeach</div><footer class="flex flex-col gap-4 bg-slate-50 px-5 py-5 sm:flex-row sm:items-center sm:justify-between sm:px-7"><div><span class="text-xs text-slate-400">订单合计</span><strong class="ml-2 text-xl">¥{{ number_format($order->amount,2) }}</strong></div><div class="flex flex-wrap gap-2">@foreach($order->actions as $action)@if($action['type']==='link')<a href="{{ $action['url'] }}" class="{{ $action['tone']==='primary' ? 'shop-button !px-4 !py-2' : 'shop-button-secondary !px-4 !py-2' }}">{{ $action['label'] }}</a>@else<button type="button" data-order-action='@json($action)' class="{{ $action['tone']==='primary' ? 'shop-button !px-4 !py-2' : 'shop-button-secondary !px-4 !py-2' }}">{{ $action['label'] }}</button>@endif @endforeach</div></footer></article>
@empty<div class="rounded-[2rem] border border-dashed border-slate-300 bg-white py-20 text-center"><h2 class="text-xl font-black">暂无订单</h2><a href="{{ url('/products') }}" class="shop-button mt-6">去逛逛</a></div>@endforelse
</div>
<dialog id="order-dialog" class="m-auto w-[min(92vw,520px)] rounded-[2rem] p-0 backdrop:bg-slate-950/50"><form method="dialog" class="p-7"><div class="flex justify-between"><h2 id="dialog-title" class="text-xl font-black">订单操作</h2><button class="text-slate-400">✕</button></div><div id="dialog-fields" class="mt-5"></div><div class="mt-6 flex justify-end gap-2"><button value="cancel" class="shop-button-secondary">取消</button><button id="dialog-submit" value="default" class="shop-button">确认</button></div></form></dialog>
@endsection
@push('scripts')
<script>
const orderDialog=document.querySelector('#order-dialog');let currentAction=null;
document.addEventListener('click',e=>{const b=e.target.closest('[data-order-action]');if(!b)return;currentAction=JSON.parse(b.dataset.orderAction);document.querySelector('#dialog-title').textContent=currentAction.label;document.querySelector('#dialog-fields').innerHTML=currentAction.type==='comment'?'<label class="grid gap-2 text-sm font-bold">评分<select id="order-star" class="rounded-xl border p-3"><option value="5">5 星</option><option value="4">4 星</option><option value="3">3 星</option><option value="2">2 星</option><option value="1">1 星</option></select></label><label class="mt-4 grid gap-2 text-sm font-bold">评价<textarea id="order-content" class="rounded-xl border p-3" rows="4"></textarea></label>':currentAction.type==='refund'?'<label class="grid gap-2 text-sm font-bold">退款原因<textarea id="refund-reason" class="rounded-xl border p-3" rows="4"></textarea></label>':'<p class="text-sm text-slate-600">确定执行此操作吗？</p>';orderDialog.showModal();});
document.querySelector('#dialog-submit')?.addEventListener('click',async e=>{e.preventDefault();if(!currentAction)return;const method=currentAction.type==='delete'?'delete':currentAction.type==='confirm'?'patch':'post';const payload=currentAction.type==='comment'?{star:document.querySelector('#order-star').value,content:document.querySelector('#order-content').value}:currentAction.type==='refund'?{refund_reason:document.querySelector('#refund-reason').value}:{};await window.axios({method,url:currentAction.url,data:payload});window.location.reload();});
</script>
@endpush
